//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WTLBuilder.rc
//
#define ID_FILE_SAVEAS_TEMPLATE         0
#define IDS_PROJNAME                    100
#define IDR_IRAD                        100
#define IDD_ABOUTBOX                    100
#define IDR_SCRIPTHOST                  101
#define IDR_MAINFRAME                   128
#define IDB_ARROW                       201
#define IDR_TOOLBAR1                    205
#define IDR_COMPONENTS                  205
#define IDD_NULL                        207
#define IDB_MINUS                       209
#define IDB_ACTIVATE                    210
#define IDI_DEFAULT                     211
#define ID_OPTIONS_OPTIONS              213
#define IDI_ALIGN_RIGHT                 216
#define IDI_ALIGN_BOTTOM                217
#define IDI_ALIGN_LEFT                  218
#define IDI_ALIGN_TOP                   219
#define IDI_ICON6                       220
#define IDI_CENTER_HORIZ                220
#define IDI_ICON7                       221
#define IDI_CENTER_VERT                 221
#define IDI_ICON8                       222
#define IDI_GS_HORIZ                    222
#define IDI_ICON9                       223
#define IDI_GS_VERT                     223
#define IDI_ICON10                      224
#define IDI_HORIZ_ORDER                 224
#define IDI_SAME_WIDTH                  225
#define IDI_NEW                         226
#define IDI_OPEN                        227
#define IDI_SAME_SIZE                   228
#define IDI_SAVE                        229
#define IDI_SAVE_ALL                    230
#define IDI_ICON17                      231
#define IDI_VERT_ORDER                  231
#define IDI_SAME_HEIGHT                 232
#define IDI_TOPARENT                    233
#define IDI_TOBACKGROUND                234
#define IDI_TOFOREGROUND                235
#define IDI_CREATION_ORDER              236
#define IDI_CENTER_GROUP_VERT           238
#define IDI_DIST_GROUP_VERT             240
#define IDI_CENTER_GROUP_HORIZ          241
#define IDI_DIST_GROUP_HORIZ            243
#define IDI_LEFT_SIDE                   246
#define IDI_RIGHT_SIDE                  247
#define IDI_TOP_SIDE                    248
#define IDI_SHOW_GRID                   249
#define IDI_ICON1                       250
#define IDI_SHOW_GSGRID                 250
#define IDI_ICON2                       251
#define IDI_CHANGEPARENT                251
#define IDI_ICON3                       252
#define IDI_TABORDER                    252
#define IDI_ICON4                       253
#define IDI_ERROR_MSG                   253
#define IDI_INFO_MSG                    254
#define IDI_WARN_MSG                    255
#define IDR_MENU1                       256
#define IDR_SCRIPT_EDITOR_MENU          256
#define IDR_SCRIPT_EDITOR               256
#define IDI_CLOSE_FORM                  260
#define IDI_SHOW_FORM                   261
#define IDI_SORT_FORM                   262
#define IDB_LOGO                        263
#define IDI_ICON5                       264
#define IDI_HORIZ_ORDER_RIGHT           264
#define IDI_VERT_ORDER_BOTTOM           265
#define IDR_TYPELIB1                    267
#define IDI_ICON11                      268
#define IDI_PROP_ICON                   268
#define IDI_ICON12                      270
#define IDI_CLEAR_ERR                   270
#define IDC_TAB1                        1006
#define IDC_TAB2                        1007
#define IDC_LIST1                       1008
#define IDC_RADIO1                      1013
#define IDC_BUTTON1                     1021
#define ID_PLACEHOLDER                  32772
#define ID_ALIGNLEFT                    32772
#define ID_ALIGNTOP                     32773
#define ID_ALIGNRIGHT                   32774
#define ID_ALIGNBOTTOM                  32775
#define ID_ALIGNHORIZ                   32776
#define ID_ALIGNVERT                    32777
#define ID_MAKESAMEWIDTH                32778
#define ID_MAKESAMEHEIGHT               32779
#define ID_MAKESAMESIZE                 32780
#define ID_MAKEGOLDENSECTIONWIDTH       32781
#define ID_MAKEGOLDENSECTIONHEIGHT      32782
#define ID_FILE_SAVEALL                 32784
#define ID_FILE_GENERATE_LOC_FILE       32785
#define ID_BUTTON32786                  32786
#define ID_TOPARENT                     32786
#define ID_EDIT_SELECTALL               32793
#define ID_UNDO                         32795
#define ID_VIEW_PROPERTY                32796
#define ID_VIEW_OUTPUT                  32797
#define IDI_FILE_SAVE                   -32734
#define ID_FILE_SAVE32803               32803
#define ID_FILE_SAVEAS                  32804
#define ID_FILE_CLOSE32805              32805
#define ID_ACCELERATOR32807             32807
#define ID_CTRL_BUILDER                 32810
#define ID_FILE_NEW_CONTROL             32811
#define ID_FILE_NEW_FORM                32812
#define ID_FILENEW                      32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        271
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
